import {
  addDoc,
  collection,
  deleteDoc,
  doc,
  getDocs,
  serverTimestamp,
  updateDoc,
  writeBatch,
} from "firebase/firestore"

import { db } from "@/lib/firebase/client"
import { documentMockData } from "./document-mock-data"
import type { Document } from "./types/document-types"

const DOCUMENTS_COLLECTION = "documents"

/**
 * Read all non-deleted documents from Firestore.
 * Soft-deleted documents (`deletedAt != null`) are filtered out.
 * The `id` field is resolved from the Firestore document ID if not stored in the document data.
 */
export async function getDocuments(): Promise<Document[]> {
  const snapshot = await getDocs(collection(db, DOCUMENTS_COLLECTION))

  const result = snapshot.docs
    .map((documentRef) => {
      const data = documentRef.data() as Document

      return {
        ...data,
        id: documentRef.id,
      }
    })
    .filter((documentItem) => !documentItem.deletedAt)

  return JSON.parse(JSON.stringify(result))
}

/**
 * Seed mock documents into Firestore.
 * Deletes all existing non-deleted documents first, then creates new ones using `addDoc`
 * so Firestore auto-generates the document ID.
 */
export async function seedDocumentsWithClient(): Promise<Document[]> {
  // 1. Clear existing documents
  const existingSnapshot = await getDocs(collection(db, DOCUMENTS_COLLECTION))
  const deleteBatch = writeBatch(db)
  existingSnapshot.docs.forEach((docSnapshot) => {
    deleteBatch.delete(doc(db, DOCUMENTS_COLLECTION, docSnapshot.id))
  })
  await deleteBatch.commit()

  // 2. Create new documents using addDoc (Firestore auto-generates IDs)
  const seedBatch = writeBatch(db)
  const docRefs: ReturnType<typeof doc>[] = []

  documentMockData.forEach((documentItem) => {
    const docRef = doc(collection(db, DOCUMENTS_COLLECTION))
    docRefs.push(docRef)
    seedBatch.set(docRef, {
      name: documentItem.name,
      status: documentItem.status,
      summary: documentItem.summary ?? "",
      folderId: documentItem.folderId ?? null,
      createdBy: documentItem.createdBy ?? "System",
      createdDate:
        documentItem.createdDate ??
        documentItem.createdAt ??
        new Date().toISOString(),
      createdAt: documentItem.createdAt ?? new Date().toISOString(),
      updatedAt: documentItem.updatedAt ?? new Date().toISOString(),
      deletedAt: null,
    })
  })

  await seedBatch.commit()
  return getDocuments()
}

/**
 * Create a new document in Firestore.
 * The document ID is auto-generated by Firestore via `addDoc`.
 */
export async function createDocument(
  documentItem: Omit<Document, "id">
): Promise<Document> {
  const now = new Date().toISOString()

  const payload = {
    name: documentItem.name,
    status: documentItem.status,
    summary: documentItem.summary ?? "",
    folderId: documentItem.folderId ?? null,
    createdBy: documentItem.createdBy ?? "Unknown",
    createdDate: documentItem.createdDate ?? now,
    createdAt: documentItem.createdAt ?? now,
    updatedAt: now,
    deletedAt: null,
  }

  const docRef = await addDoc(collection(db, DOCUMENTS_COLLECTION), payload)

  return { ...payload, id: docRef.id }
}

export async function updateDocument(
  documentItem: Document
): Promise<Document> {
  const payload: Document = {
    ...documentItem,
    updatedAt: new Date().toISOString(),
  }

  await updateDoc(doc(db, DOCUMENTS_COLLECTION, documentItem.id), payload)

  return payload
}

/**
 * Soft delete a document by setting `deletedAt` to a server timestamp.
 * The document row stays in Firestore but is filtered out by `getDocuments()`.
 */
export async function deleteDocument(documentId: string): Promise<void> {
  const documentRef = doc(db, DOCUMENTS_COLLECTION, documentId)
  await updateDoc(documentRef, {
    deletedAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  })
}

export function getDocumentStats(documents: Document[]) {
  const total = documents.length

  return {
    total,
    draft: documents.filter((item) => item.status === "draft").length,
    published: documents.filter((item) => item.status === "published").length,
  }
}
