import {
  ChevronDown,
  ChevronUp,
  CheckCircle2,
  Circle,
  Clock,
  Minus,
  PlayCircle,
  UserPlus,
  UserCheck,
  HandHeart,
  UserMinus,
} from "lucide-react"

import { customerSchema } from "./types/customer-types"

export const services = [
  {
    value: "web-development",
    label: "Web Development",
  },
  {
    value: "mobile-app",
    label: "Mobile App",
  },
  {
    value: "ui-ux-design",
    label: "UI/UX Design",
  },
  {
    value: "digital-marketing",
    label: "Digital Marketing",
  },
  {
    value: "consulting",
    label: "Consulting",
  },
  {
    value: "cloud-infrastructure",
    label: "Cloud Infrastructure",
  },
  {
    value: "seo",
    label: "SEO",
  },
  {
    value: "maintenance",
    label: "Maintenance & Support",
  },
]

export const statuses = [
  {
    value: "new",
    label: "New",
    icon: UserPlus,
  },
  {
    value: "contacted",
    label: "Contacted",
    icon: HandHeart,
  },
  {
    value: "in progress",
    label: "In Progress",
    icon: PlayCircle,
  },
  {
    value: "converted",
    label: "Converted",
    icon: UserCheck,
  },
  {
    value: "lost",
    label: "Lost",
    icon: UserMinus,
  },
]

export const priorities = [
  {
    label: "Low",
    value: "low",
    icon: ChevronDown,
  },
  {
    label: "Medium",
    value: "medium",
    icon: Minus,
  },
  {
    label: "High",
    value: "high",
    icon: ChevronUp,
  },
  {
    label: "VIP",
    value: "vip",
    icon: CheckCircle2,
  },
]

const customersData = [
  {
    id: "CUS-1001",
    fullName: "Nguyễn Văn An",
    email: "an.nguyen@example.com",
    phoneNumber: "0901234567",
    serviceName: "web-development",
    status: "converted",
    priority: "vip",
    userId: "",
    createdAt: "2025-01-15T08:00:00.000Z",
  },
  {
    id: "CUS-1002",
    fullName: "Trần Thị Bình",
    email: "binh.tran@example.com",
    phoneNumber: "0912345678",
    serviceName: "ui-ux-design",
    status: "in progress",
    priority: "high",
    userId: "",
    createdAt: "2025-02-03T10:30:00.000Z",
  },
  {
    id: "CUS-1003",
    fullName: "Lê Hoàng Long",
    email: "long.le@example.com",
    phoneNumber: "0923456789",
    serviceName: "mobile-app",
    status: "new",
    priority: "medium",
    userId: "",
    createdAt: "2025-03-12T14:15:00.000Z",
  },
  {
    id: "CUS-1004",
    fullName: "Phạm Minh Châu",
    email: "chau.pham@example.com",
    phoneNumber: "0934567890",
    serviceName: "digital-marketing",
    status: "contacted",
    priority: "high",
    userId: "",
    createdAt: "2025-03-20T09:45:00.000Z",
  },
  {
    id: "CUS-1005",
    fullName: "Đỗ Thanh Hằng",
    email: "hang.do@example.com",
    phoneNumber: "0945678901",
    serviceName: "consulting",
    status: "lost",
    priority: "low",
    userId: "",
    createdAt: "2025-04-01T11:00:00.000Z",
  },
  {
    id: "CUS-1006",
    fullName: "Vũ Đức Nam",
    email: "nam.vu@example.com",
    phoneNumber: "0956789012",
    serviceName: "cloud-infrastructure",
    status: "converted",
    priority: "high",
    userId: "",
    createdAt: "2025-04-10T13:20:00.000Z",
  },
  {
    id: "CUS-1007",
    fullName: "Bùi Thị Mai",
    email: "mai.bui@example.com",
    phoneNumber: "0967890123",
    serviceName: "seo",
    status: "in progress",
    priority: "medium",
    userId: "",
    createdAt: "2025-05-05T15:10:00.000Z",
  },
  {
    id: "CUS-1008",
    fullName: "Hoàng Văn Đức",
    email: "duc.hoang@example.com",
    phoneNumber: "0978901234",
    serviceName: "web-development",
    status: "new",
    priority: "vip",
    userId: "",
    createdAt: "2025-05-18T08:45:00.000Z",
  },
  {
    id: "CUS-1009",
    fullName: "Ngô Thanh Tùng",
    email: "tung.ngo@example.com",
    phoneNumber: "0989012345",
    serviceName: "maintenance",
    status: "contacted",
    priority: "medium",
    userId: "",
    createdAt: "2025-06-02T10:00:00.000Z",
  },
  {
    id: "CUS-1010",
    fullName: "Đặng Thị Lan",
    email: "lan.dang@example.com",
    phoneNumber: "0123456789",
    serviceName: "mobile-app",
    status: "in progress",
    priority: "high",
    userId: "",
    createdAt: "2025-06-15T16:30:00.000Z",
  },
  {
    id: "CUS-1011",
    fullName: "Phan Văn Hải",
    email: "hai.phan@example.com",
    phoneNumber: "0234567890",
    serviceName: "ui-ux-design",
    status: "converted",
    priority: "medium",
    userId: "",
    createdAt: "2025-06-20T09:15:00.000Z",
  },
  {
    id: "CUS-1012",
    fullName: "Võ Thị Hồng",
    email: "hong.vo@example.com",
    phoneNumber: "0345678901",
    serviceName: "consulting",
    status: "lost",
    priority: "low",
    userId: "",
    createdAt: "2025-07-01T14:00:00.000Z",
  },
  {
    id: "CUS-1013",
    fullName: "Đinh Quốc Bảo",
    email: "bao.dinh@example.com",
    phoneNumber: "0456789012",
    serviceName: "cloud-infrastructure",
    status: "new",
    priority: "vip",
    userId: "",
    createdAt: "2025-07-10T11:25:00.000Z",
  },
  {
    id: "CUS-1014",
    fullName: "Lương Thị Kim",
    email: "kim.luong@example.com",
    phoneNumber: "0567890123",
    serviceName: "digital-marketing",
    status: "contacted",
    priority: "high",
    userId: "",
    createdAt: "2025-07-15T08:50:00.000Z",
  },
  {
    id: "CUS-1015",
    fullName: "Trịnh Văn Sơn",
    email: "son.trinh@example.com",
    phoneNumber: "0678901234",
    serviceName: "seo",
    status: "in progress",
    priority: "medium",
    userId: "",
    createdAt: "2025-07-20T13:40:00.000Z",
  },
]

export const customerMockData = customerSchema.array().parse(customersData)
